compilers:
- compiler:
    paths:
      cc: /apps/gcc/8.2.0/x86_64/bin/gcc
      cxx: /apps/gcc/8.2.0/x86_64/bin/g++
      f77: /apps/gcc/8.2.0/x86_64/bin/gfortran
      fc: /apps/gcc/8.2.0/x86_64/bin/gfortran
    operating_system: centos7
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@8.2.0

