packages:
  all:
    compiler: [gcc@9.3.0]
    target: [skylake_avx512]
    providers:
      mpi: [mpich]
      blas: [openblas]
      lapack: [openblas]
  mpi:
    require: 'mpich'
  mpich:
    variants: netmod=ucx device=ch4 +slurm +hydra
  libfabric:
    variants: fabrics=verbs
  ucx:
    variants: +optimizations+gdrcopy
    version: [1.8.1]
  openmpi:
    require: "@4.1.4"
    buildable: false
    externals:
    - spec: openmpi@4.1.4
      prefix: /apps/exawind/2023-11/x86_64/openmpi-4.1.4
  curl:
    require: "@7.29.0"
    externals:
    - spec: curl@7.29.0
      prefix: /usr/bin/curl
    buildable: False
  slurm:
    externals:
    - spec: slurm@20.11.9
      prefix: /apps/slurm/x86/20.11.9-rdhpc8
    buildable: False
