packages:
  amr-wind:
    variants: +tiny_profile
  trilinos:
    variants: ~adelus~adios2~amesos~amesos2~anasazi+aztec~basker~belos~boost~chaco~complex~dtk~epetra~epetraext~epetraextbtf~epetraextexperimental~epetraextgraphreorderings~float~fortran~hypre~ifpack~ifpack2~intrepid~intrepid2~ipo~isorropia~mesquite~minitensor~ml~muelu~mumps~nox~openmp~panzer~phalanx~piro~python~rol~rythmos~sacado~scorec~shards~shylu~stk_simd~stk_unit_tests~stokhos~stratimikos~strumpack~suite-sparse~superlu~superlu-dist~teko~tempus~test~thyra~trilinoscouplings~x11~zoltan2 generator=ninja

#
# 1. This is how nalu-wind was previously built for TotalEnergies scaling studies
#
#   TPLs: Boost, HDF5, netCDF, STK, Trilinos, yaml-cpp and zlib
#   Optional TPLs enabled: OpenFAST, Hypre, TIOGA
#
# 2. Here were the defaults from below with ~trilinos-solvers
#
#   TPLs: Boost, HDF5, netCDF, STK, Trilinos, yaml-cpp and zlib
#   Optional TPLs enabled: OpenFAST, Hypre, TIOGA
#
# But I got the following error when I ran with #2
#
#   what():  Trilinos solver support must be enabled during compile time.
#
#  ascent:
#    variants: ~fortran~openmp
#  nalu-wind:
#    variants: +trilinos-solvers
