compilers:
- compiler:
    spec: gcc@13.2.0
    paths:
      cc:  /lustre/p4scratch/data_local/sw/RHEL8/spack-0.21.0/opt/gcc-8.5.0/gcc-13.2.0-5x55s4v/bin/gcc
      cxx: /lustre/p4scratch/data_local/sw/RHEL8/spack-0.21.0/opt/gcc-8.5.0/gcc-13.2.0-5x55s4v/bin/g++
      f77: /lustre/p4scratch/data_local/sw/RHEL8/spack-0.21.0/opt/gcc-8.5.0/gcc-13.2.0-5x55s4v/bin/gfortran
      fc:  /lustre/p4scratch/data_local/sw/RHEL8/spack-0.21.0/opt/gcc-8.5.0/gcc-13.2.0-5x55s4v/bin/gfortran
    flags: {}
    operating_system: rhel8
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths:
     - /lustre/p4scratch/data_local/sw/RHEL8/spack-0.21.0/opt/gcc-8.5.0/gcc-13.2.0-5x55s4v/lib64

#- compiler:
#    paths:
#      cc: /usr/bin/gcc
#      cxx: /usr/bin/g++
#      f77: /usr/bin/gfortran
#      fc: /usr/bin/gfortran
#    operating_system: rhel8
#    target: x86_64
#    modules: []
#    environment: {}
#    extra_rpaths: []
#    flags: {}
#    spec: gcc@8.5.0
#- compiler:
#    paths:
#      cc: /apps/gcc/8.2.0/x86_64/bin/gcc
#      cxx: /apps/gcc/8.2.0/x86_64/bin/g++
#      f77: /apps/gcc/8.2.0/x86_64/bin/gfortran
#      fc: /apps/gcc/8.2.0/x86_64/bin/gfortran
#    operating_system: rocky9
#    target: x86_64
#    modules: []
#    environment: {}
#    extra_rpaths: []
#    flags: {}
#    spec: gcc@8.2.0

