spack:
  concretizer:
    unify: false
    reuse: false 
  view: false
  specs:
  specs:
    - 'exawind@master~amr_wind_gpu~nalu_wind_gpu ^amr-wind@3.6.0+openfast+waves2amr+netcdf+hdf5 ^openfast@4.1.1+rosco+openmp+fastfarm %gcc'

    #- 'exawind@master~amr_wind_gpu~nalu_wind_gpu ^amr-wind@3.6.0+openfast+waves2amr+netcdf+hdf5 ^openfast@4.1.1+rosco+openmp+fastfarm %openmpi'
    #- 'exawind@master~amr_wind_gpu~nalu_wind_gpu ^amr-wind@3.4.0 %gcc'

    # - 'exawind@master~amr_wind_gpu~nalu_wind_gpu ^amr-wind@main %gcc'
    # - 'exawind@terrain~amr_wind_gpu~nalu_wind_gpu %gcc'
    #- 'exawind@terrain~amr_wind_gpu~nalu_wind_gpu %oneapi'

    #- 'netcdf-c%oneapi'
    #- 'amr-wind@terrain+netcdf %oneapi'

    #- 'amr-wind@terrain+netcdf%oneapi %oneapi'
    #- 'nalu-wind%oneapi'

    #- 'exawind~amr_wind_gpu~nalu_wind_gpu %oneapi'
      #- 'amr-wind@terrain %oneapi'
      #- 'exawind~amr_wind_gpu~nalu_wind_gpu %gcc'
      #- 'exawind+amr_wind_gpu~nalu_wind_gpu+cuda %gcc'
      #- 'exawind~amr_wind_gpu+nalu_wind_gpu+cuda %gcc'
      #- 'exawind+amr_wind_gpu+nalu_wind_gpu+cuda %gcc'
