packages:
  cray-mpich:
    require: "@=8.1.28"
    buildable: false
    externals:
      - spec: "cray-mpich@=8.1.28%oneapi@2023.2.0"
        prefix: /opt/cray/pe/mpich/8.1.28/ofi/intel/2022.1
        modules:
          - libfabric/1.15.2.0
      - spec: "cray-mpich@=8.1.28%gcc@12.2.0"
        prefix: /opt/cray/pe/mpich/8.1.28/ofi/gnu/10.3
        modules:
          - libfabric/1.15.2.0
      - spec: "netcdf-c@4.9.2"
        prefix: /nopt/nrel/apps/cpu_stack/libraries-craympich/06-24/linux-rhel8-sapphirerapids/oneapi-2023.2.0/netcdf-c-4.9.2-3q6roxfm5g7tp77ivfbvvsiqgwmvrzxm
        modules:
          - netcdf-c/4.9.2-cray-mpich-intel

  mpi:
    require: "cray-mpich@8.1.28"
  blas:
    require: "openblas"
  lapack:
    require: "openblas"
  amr-wind:
    require: "netcdf-c@4.9.2"
  all:
    variants: cuda_arch=90
