spack:
  concretizer:
    unify: false
    reuse: false 
  view: false
  specs:
    - 'netcdf%oneapi'

    #- 'amr-wind@hgopalan-terrain+netcdf%oneapi %oneapi'
    #- 'nalu-wind%oneapi'


    #- 'exawind~amr_wind_gpu~nalu_wind_gpu %oneapi'
      #- 'amr-wind@hgopalan-terrain %oneapi'
      #- 'exawind~amr_wind_gpu~nalu_wind_gpu %gcc'
      #- 'exawind+amr_wind_gpu~nalu_wind_gpu+cuda %gcc'
      #- 'exawind~amr_wind_gpu+nalu_wind_gpu+cuda %gcc'
      #- 'exawind+amr_wind_gpu+nalu_wind_gpu+cuda %gcc'
