compilers:

- compiler:
    spec: gcc@13.3.0
    paths:
      cc: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs/bin/gcc
      cxx: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs/bin/g++
      f77: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs/bin/gfortran
      fc: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs/bin/gfortran
    flags: {}
    operating_system: rocky9
    target: x86_64
    modules: [ gcc/13.3.0 ]
    environment: {}
    extra_rpaths: []
    
- compiler:
    spec: gcc@13.3.0-optimized
    paths:
      cc: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs/bin/gcc
      cxx: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs/bin/g++
      f77: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs/bin/gfortran
      fc: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs/bin/gfortran
    flags:
      cflags:   '-march=native -mtune=native -ftree-vectorize -fPIC -pipe -Ofast'
      cxxflags: '-march=native -mtune=native -ftree-vectorize -fPIC -pipe -Ofast'
      fflags:   '-march=native -mtune=native'
      cppflags: '-DNDEBUG'
    operating_system: rocky9
    target: x86_64
    modules: [ gcc/13.3.0 ]
    environment: {}
    extra_rpaths: []

#    flags: {}
#
#- compiler:
#    paths:
#      cc: /apps/gcc/8.2.0/x86_64/bin/gcc
#      cxx: /apps/gcc/8.2.0/x86_64/bin/g++
#      f77: /apps/gcc/8.2.0/x86_64/bin/gfortran
#      fc: /apps/gcc/8.2.0/x86_64/bin/gfortran
#    flags:
#      cflags: '-march=native -mtune=native -ftree-vectorize -fPIC -pipe -Ofast -DNDEBUG'
#      cxxflags: '-fvisibility-inlines-hidden -fmessage-length=0 -march=native -mtune=native -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -ffunction-sections -pipe -Ofast -DNDEBUG'
#    operating_system: rocky9
#    target: x86_64
#    modules: []
#    environment: {}
#    extra_rpaths: []
#    flags: {}
#    spec: gcc@8.2.0

