compilers:
- compiler:
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    operating_system: rocky9
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@11.4.1
#- compiler:
#    paths:
#      cc: /apps/gcc/8.2.0/x86_64/bin/gcc
#      cxx: /apps/gcc/8.2.0/x86_64/bin/g++
#      f77: /apps/gcc/8.2.0/x86_64/bin/gfortran
#      fc: /apps/gcc/8.2.0/x86_64/bin/gfortran
#    operating_system: rocky9
#    target: x86_64
#    modules: []
#    environment: {}
#    extra_rpaths: []
#    flags: {}
#    spec: gcc@8.2.0

