packages:
  gcc:
    externals:
    - spec: gcc@13.3.0 languages:='c,c++,fortran'
      prefix: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs
      modules:
      - gcc/13.3.0
      extra_attributes:
        compilers:
          c: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs/bin/gcc
          cxx: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs/bin/g++
          fortran: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs/bin/gfortran
        flags:
          cflags: -march=native -mtune=native -ftree-vectorize -fPIC -pipe -Ofast -Wno-error
          cxxflags: -march=native -mtune=native -ftree-vectorize -fPIC -pipe -Ofast -Wno-error
          fflags: -march=native -mtune=native
          cppflags: -DNDEBUG
        environment: {}
        extra_rpaths: []
    - spec: gcc-noflags@13.3.0 languages:='c,c++,fortran'
      prefix: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs
      modules:
      - gcc/13.3.0
      extra_attributes:
        compilers:
          c: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs/bin/gcc
          cxx: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs/bin/g++
          fortran: /hrtc/apps/devtools/spack/PINE/linux-rocky9-zen4/gcc-11.4.1/gcc-13.3.0-s6z5ak5dds7jmlohxs2bctxhyhgfwhgs/bin/gfortran
        flags: {}
        environment: {}
        extra_rpaths: []
  mpi:
    require: 'openmpi@4.1.4'
    #require: 'openmpi@5.0.5'
  mpich:
    variants: netmod=ucx device=ch4 +slurm +hydra
  ucx:
    variants: +verbs
  curl:
    require: "@7.76.1"
    externals:
    - spec: curl@7.76.1
      prefix: /usr/bin/curl
    buildable: False
  slurm:
    externals:
    - spec: slurm@23.11.6
      prefix: /apps/slurm/x86/23.11.6-pine
    buildable: False
  blas:
    require: "openblas"
  lapack:
    require: "openblas"
  openmpi:
    require: "@4.1.4"
    buildable: false
    externals:
    - spec: openmpi@4.1.4
      prefix: <BUILD_DIR>/openmpi-4.1.4/
    - spec: openmpi@5.0.5
      prefix: /hrtc/apps/mpi/openmpi/x86_64/rocky9/5.0.5/gcc/13.3.0/nocuda/
  nalu-wind:
    require: +trilinos-solvers
  amr-wind:
    variants: +tiny_profile +openfast +netcdf
  openfast:
    variants: +openmp +shared +rosco +fastfarm +netcdf
  openblas:
    require: "%gcc-noflags@13.3.0"
  all:
    require: "%gcc@13.3.0"
    providers:
      mpi: [openmpi]
      blas: [openblas]
      lapack: [openblas]
      c: [gcc-optimized@13.3.0]
      cxx: [gcc-optimized@13.3.0]
      fortran:  [gcc-optimized@13.3.0]
    #target: [zen4]
      

  #all:
  #  compilers: [gcc@13.3.0-optimized]
  #  providers:
  #    mpi: [openmpi]
  #    blas: [openblas]
  #    lapack: [openblas]

    #variants: ~openmp +shared +rosco +fastfarm +netcdf

#  amr-wind:
#    require: "@3.4.0"
#    variants: +tiny_profile +openfast@4.0.2 ^openfast+openmp+shared+rosco
#
#      prefix: $spack/../../openmpi-4.1.4/
#      prefix: /shared/data1/Projects/WIND/apps/exawind/2024-09/genoa/exawind-terrain/openmpi-4.1.4/
#
#      prefix: /apps/exawind/2024-09/genoa_x86_64/exawind-terrain/openmpi-4.1.4/
#
#  openmpi:
#    variants: +pmi +cuda fabrics=verbs schedulers=slurm legacylaunchers=true ~vt
#  mpich:
#    variants: netmod=ucx device=ch4 +slurm +hydra
#  nalu-wind:
#    variants: +openfast~wind-utils+boost+trilinos-solvers
#  openmpi:
#    require: "@4.1.4"
#    buildable: false
#    externals:
#    - spec: openmpi@4.1.4
#      prefix: /apps/exawind/2023-11/x86_64/openmpi-4.1.4
#  openmpi:
#    require:
#      - "@4.1.6"
#      - "cflags='-I/usr/include/infiniband'"
#
#
#  OpenMPI with ucx - haven't tried
#
#  openmpi:
#    require: "@4.1.6"
#    variants: fabrics=ucx schedulers=slurm legacylaunchers=true ~vt
#  ucx:
#    variants: +verbs
#  libfabric:
#    variants: fabrics=verbs,mlx,ucx,sockets,tcp,udp,shm


