spack:
  concretizer:
    unify: false
    reuse: false 
  view: false
  specs:
    - 'exawind~amr_wind_gpu~nalu_wind_gpu %gcc'

    #- 'exawind@terrain~amr_wind_gpu~nalu_wind_gpu %gcc'

    #- 'exawind@terrain~amr_wind_gpu~nalu_wind_gpu %oneapi'

    #- 'netcdf-c%oneapi'
    #- 'amr-wind@terrain+netcdf %oneapi'

    #- 'amr-wind@terrain+netcdf%oneapi %oneapi'
    #- 'nalu-wind%oneapi'

    #- 'exawind~amr_wind_gpu~nalu_wind_gpu %oneapi'
      #- 'amr-wind@terrain %oneapi'
      #- 'exawind~amr_wind_gpu~nalu_wind_gpu %gcc'
      #- 'exawind+amr_wind_gpu~nalu_wind_gpu+cuda %gcc'
      #- 'exawind~amr_wind_gpu+nalu_wind_gpu+cuda %gcc'
      #- 'exawind+amr_wind_gpu+nalu_wind_gpu+cuda %gcc'
