packages:
  gcc:
    externals:
      - spec: gcc@15.2.1 languages='c,c++,fortran'
        prefix: /usr
        extra_attributes:
          compilers:
            c: /usr/bin/gcc
            cxx: /usr/bin/g++
            fortran: /usr/bin/gfortran
          flags:
            cflags: -O3 -march=native -mtune=native -fPIC
            cxxflags: -O3 -march=native -mtune=native -fPIC
            fflags: -O3 -march=native -mtune=native
    buildable: false
  amd-aocc:
    externals:
      - spec: amd-aocc@5.1.0 languages='c,c++,fortran'
        prefix: /opt/AMD/aocc-compiler-5.1.0
        extra_attributes:
          compilers:
            c: /opt/AMD/aocc-compiler-5.1.0/bin/clang 
            cxx: /opt/AMD/aocc-compiler-5.1.0/bin/clang++
            fortran: /opt/AMD/aocc-compiler-5.1.0/bin/flang
    buildable: false
  amd-aocl:
    externals:
    - spec: amd-aocl@5.2.0
      prefix: /opt/AMD/aocl/aocl-linux-aocc-5.2.0/aocc
    buildable: false
  mpi:
    require: 'openmpi@4.1.4'
  cmake:
    externals:
    - spec: cmake@3.31.10
      prefix: /usr
    buildable: false
  openmpi:
    require: "@4.1.4"
    buildable: false
    externals:
    - spec: openmpi@4.1.4
      prefix: <BUILD_DIR>/openmpi-4.1.4/
  curl:
    externals:
    - spec: curl@8.15.0
      prefix: /usr
    buildable: False
  hypre:
    flags:
      cflags: -O3 -march=native -mtune=native -fPIC -std=gnu17
  all:
    prefer:
      - "%clang@17.0.6"
    providers:
      mpi: [openmpi]
      blas: [openblas, amd-aocl]
      lapack: [openblas, amd-aocl]
      c: [gcc, amd-aocc]
      cxx: [gcc, amd-aocc]
      fortran: [gcc, amd-aocc]
