spack:
  concretizer:
    unify: false
    reuse: false
  view: false
  specs:
    - 'exawind@master~amr_wind_gpu~nalu_wind_gpu~nalu_wind~rocm %gcc ^amr-wind@3.8.1+openfast+waves2amr+netcdf+hdf5 ^openfast@4.1.1+rosco+openmp+fastfarm'

    #- 'exawind@master~amr_wind_gpu~nalu_wind_gpu~nalu_wind ^amr-wind@3.6.0+openfast+waves2amr+netcdf+hdf5 ^openfast@4.1.1+rosco+openmp+fastfarm %clang'
    #- 'exawind@master~amr_wind_gpu~nalu_wind_gpu ^amr-wind@3.6.0+netcdf+hdf5 %clang'
